name: basic-ci

on: push

jobs:
  ci:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: run
        run: |
          npm run lint
          npm run ts:check
          npm run test
          npm run format -- --check
